### ISSUE TITLE
add Resource / data to manage management_cluster

### ISSUE THREAD

**Issue by Davidffry** [vmware/terraform-provider-tanzu-mission-control#131]
### Is your feature request related to a problem? Please describe.

I would like to manage the management cluster via terraform, there are any ways to do this not by the UI ?

### Describe the solution you'd like

A resource / data to manage the management_cluster

**Comment by Vasundharashukla** [comment]
Hi @Davidffry,

The management cluster feature is currently not supported by the Terraform provider, but it is in the roadmap to be supported soon. 

cc: @sbasu31
