### ISSUE TITLE
Can't resize tkg_vsphere node pools 

### ISSUE THREAD

**Issue by manuel-hiller-ebm** [vmware/terraform-provider-tanzu-mission-control#151]
### Describe the bug

During my tests with the terraform tmc provider I noticed that I can't resize an existing node pool. I got the following error. I'm using the tmc provider version 1.1.7 and the terraform version 1.4.5.
```
│ Error: TKGs vsphere nodepool spec has to be provided
│ 
│   with tanzu-mission-control_cluster_node_pool.node_pool,
│   on main.tf line 119, in resource "tanzu-mission-control_cluster_node_pool" "node_pool":
│  119: resource "tanzu-mission-control_cluster_node_pool" "node_pool" {
│ 
╵
```

### Reproduction steps

1.Generate tmc cluster
2. Resize an existing node pool
```terraform
resource "tanzu-mission-control_cluster_node_pool" "node_pool" {
  
  management_cluster_name = "${local.raw_settings.management_cluster_name}"
  provisioner_name    = "${local.raw_settings.provisioner_name}"
  cluster_name           = "${local.raw_settings.name}"
  name                        = ${local.raw_settings.spec.topology.node_pools.info.name}
  spec {
    worker_node_count = "${local.raw_settings.spec.topology.node_pools.spec.worker_node_count}"
    tkg_vsphere {
      vm_config {
        cpu       = "${local.raw_settings.spec.topology.node_pools.spec.tkg_vsphere.vm_config.cpu}"
        disk_size = "${local.raw_settings.spec.topology.node_pools.spec.tkg_vsphere.vm_config.disk_size}"
        memory    = "${local.raw_settings.spec.topology.node_pools.spec.tkg_vsphere.vm_config.memory}"
      }
    }
  }
}
```

### Expected behavior

According to the documentation (https://registry.terraform.io/providers/vmware/tanzu-mission-control/latest/docs/resources/cluster_node_pool#nested-schema-for-spectkg_vsphere) I would have expected, that my existing node pool will be resized to the the number of the the worker_node_count value.

I hope this can be reproduced.

Thank you and best regards
Manuel

**Comment by shreyassreenivas** [comment]
@manuel-hiller-ebm , The resize of the node pool should be working and we will verify this functionality again.

This error message "Error: TKGs vsphere nodepool spec has to be provided"
will be shown during create flow and resize of the nodepool is update scenario, this is my confusion. 

I will get back to you if we have some questions/help on this issue.
