### ISSUE TITLE
Support ClusterClass based deployments

### ISSUE THREAD

**Issue by lgustafson** [vmware/terraform-provider-tanzu-mission-control#153]
### Is your feature request related to a problem? Please describe.

Since TKG 2.x, TKG uses ClusterClass-based deployments.  I was not able to deploy a cluster on a TKG 2.0 environment when using this provider.  After digging into the API, I can see that significant request body changes are required and it doesn't appear to have been implemented in this provider yet. 

### Describe the solution you'd like

Please add support for ClusterClass-based deployments so this provider is usable for TKG 2.x.

**Comment by ramya-bangera** [comment]
@lgustafson , We are working on adding the support for TKG 2.x ClusterClass based deployments. As of now this support is support is not available.

**Comment by willbush** [comment]
@ramya-bangera I'm new to Tanzu and terraform. I was trying to create a test cluster and keep getting this error:

>Error: Unable to create Tanzu Mission Control cluster entry, name : test-cluster04: POST request failed with status : 400 Bad Request, response: {"error":"Kubernetes clusters in vSphere 8.0+ must be using ClusterClass, for more information see https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzumc-using/GUID-41DE8F22-56B8-4669-AF3F-E4B4372BDB9E.html","code":9,"message":"Kubernetes clusters in vSphere 8.0+ must be using ClusterClass, for more information see https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzumc-using/GUID-41DE8F22-56B8-4669-AF3F-E4B4372BDB9E.html"}

Is it basically not possible to use terraform to create k8s cluster with vSphere 8.0+ at the moment? Or is there a way to get it to use TKG 1.x instead of 2.x?

**Comment by ramya-bangera** [comment]
@willbush, Unfortunately as of now there is no way to get terraform create cluster with vSphere 8.0+. It is available with TKG2.x and we are actively working on adding the terraform support for the same. This is a currently a work in progress and the support should be available shortly, please stay tuned for the update.

**Comment by ramya-bangera** [comment]
There is an open issue##115 tracking the same feature request. Closing this issue as duplicate
