### ISSUE TITLE
EKS Cluster Deletion Deletes Node Pool, but not Cluster

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/terraform-provider-tanzu-mission-control#178]
### Describe the bug

I'm using TMC Provider 1.1.7.  6 times I created an eks cluster.  I then removed the cluster from the TF module and re-applied.  In 5 of the 6 tries the nodepool was deleted, but not the eks cluster.  TMC shows detaching.  EKS shows active EKS cluster with no nodepools.  When I've then run terraform plan with the same module, it indicates no changes necessary.  If I then choose to add the cluster back, the terraform plan shows it should create a cluster, but terraform apply fails because cluster is in deleted staet.

### Reproduction steps

1. Create a EKSCluster with 1 nodepool
2. Delete the EKSCluster (doesn't fully complete, TMC UI shows detaching)
3. Terraform plan (shows no changes)
4. Update terraform to recreate the cluster and run terraform plan (shows a new cluster should be created)
5. Apply, and it deletees.
...

### Expected behavior

Removal of a ekscluster from TF after itis created should completely delete the cluster from TMC and EKS

If a cluster is in detaching / deleting state, then the terraform plan should indicate that a cluster exists.

**Comment by ramya-bangera** [comment]
Hi @asutoshpalai - Assigning this issue to you as it is EKS related, feel free to reassign if it will be picked by others

**Comment by vmw-vjn** [comment]
I see that EKS team has fixed a bug for "Delete pinniped created load balancer when deleting EKS cluster" - OLYMP-39798. So can we confirm the issue report again, as the fix (OLYMP-39798) goes live.

**Comment by doddatpivotal** [comment]
I just retested and it failed with the same result.

**Comment by ramya-bangera** [comment]
@asutoshpalai - Is this issue is fixed or it is still open?

**Comment by doddatpivotal** [comment]
It is no longer an issue with the 1.2.0 release
