### ISSUE TITLE
EKS Cluster Ready Wait Timeout should default to 30m, but is actually 3m

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/terraform-provider-tanzu-mission-control#181]
### Describe the bug

Version 1.1.7

Documentation provided at the terraform marketplace says that the `ready_wait_timeout` has a default value of 30m, however that is not what is happening.  It is much shorter.

I have found at https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/internal/resources/ekscluster/resource_ekscluster.go#L34 that the code sets the default to 3m.

### Reproduction steps

1. Create an eks cluster.  After about 3 minutes, it will report back successful.
2. Go to TMC UI and see the cluster is still creating.

### Expected behavior

The terraform provider should wait up to 30m for the eks cluster to be ready before reporting back status.

### Additional context

https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/resource_templates/ekscluster.tf has indicated in comments that 30m is the default.

3m is not realistic to expect a EKS cluster to be created.  In my experience a small cluster with 3 nodes takes about 12 minutes.

**Comment by vmw-vjn** [comment]
Assigning to @asutoshpalai - to continue the conversation/investigation.
