### ISSUE TITLE
Unable to scale node pool 

### ISSUE THREAD

**Issue by JuanFCabrera** [vmware/terraform-provider-tanzu-mission-control#248]
### Describe the bug

Using Release Version 1.2.2 

running terraform apply to scale node pool results in error below:

Error: Unable to update Tanzu Mission Control EKS cluster's nodepools, name : sandbox-tap-full: failed to update existing nodepools: failed to update nodepool np-01: PUT request failed with status : 400 Bad Request, response: {"error":"validating the inputs against available options in AWS failed: rpc error: code = InvalidArgument desc = release version only supported for version 1.26.6-20230816","code":3,"message":"validating the inputs against available options in AWS failed: rpc error: code = InvalidArgument desc = release version only supported for version 1.26.6-20230816"}

Terraform Plan : 
Terraform will perform the following actions:

  module.k8s-clusters.tanzu-mission-control_ekscluster.sandbox-tap-full[0] will be updated in-place
  ~ resource "tanzu-mission-control_ekscluster" "sandbox-tap-full" {
        id              = "c:01H8KR93XB2ME5FFS8YP518YC3"
        name            = "sandbox-tap-full"
        # (3 unchanged attributes hidden)

      ~ spec {
            # (1 unchanged attribute hidden)

          ~ nodepool {

              ~ spec {
                    tags           = {}
                    # (7 unchanged attributes hidden)

                  ~ scaling_config {
                      ~ desired_size = 1 -> 3
                        # (2 unchanged attributes hidden)
                    }

                    # (2 unchanged blocks hidden)
                }

                # (1 unchanged block hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Terraform node pool config : 
nodepool {
      info {
        name        = "np-01"
        description = "default node pool"
      }

      spec {
        role_arn       = var.arn_worker

        ami_type       = "AL2_x86_64"
        capacity_type  = "ON_DEMAND"
        root_disk_size = 70 // Default: 20GiB
        #tags           = { "nptag" : "nptagvalue9" }
        #node_labels    = { "nplabelkey" : "nplabelvalue" }

        subnet_ids        = var.subnet_ids
        remote_access {
          ssh_key         = var.ssh_key_name
          security_groups = var.ssh_security_groups
        }

        scaling_config {
          desired_size = 3
          max_size     = 5
          min_size     = 1
        }

        update_config {
          max_unavailable_nodes = "1"
        }

        instance_types = [
          "c5.2xlarge"
        ]

      }
    }

### Reproduction steps

1. update node pool config to desired size
2. run terraform plan
3. run terraform apply
...

### Expected behavior

Node Pool is scaled to desired size.

### Additional context

i am able to scale the Node Pool directly in TMC or AWS without issues. this is only happening with Terraform.

**Comment by ramya-bangera** [comment]
Looks something related to AMI release version but I am not so sure, @asutoshpalai - can you please check?

**Comment by gargi** [comment]
Yes, this was fixed in the v1.2.4 release
