### ISSUE TITLE
Ability to wait until the cluster is healthy

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/terraform-provider-tanzu-mission-control#25]
### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Describe the solution you'd like

I applied a terraform module that had a cluster defined.  It ran through super quick.  I'd like to see a means where I could wait until the creation of the cluster either failed or succeeded.

**Comment by shobha2626** [comment]
@doddatpivotal we have a flag (`wait_until_ready`) option you could use while creating a cluster, when set to true we wait (3 minutes by default) till the cluster comes up healthy.

Please refer to the example - https://github.com/vmware/terraform-provider-tanzu-mission-control/blob/main/docs/resources/tmc_cluster.md#example-usage

**Comment by doddatpivotal** [comment]
I missed that.  I see it now.  Thank you.  For reference, it took my TKGS cluster 15 minutes to be created.  I don't 3 minutes will be long enough.  Perhaps it can be specified by the user?

**Comment by shreyassreenivas** [comment]
We have added a new attribute in cluster resource "ready_wait_timeout". Setting this new value will ensure that the provider will wait until the cluster is marked as READY till the timeout value is elapsed.

eg  : ready_wait_timeout = "15m", will make the provider max wait for 15 mins
