### ISSUE TITLE
Ability to Provision TKGm Clusters on AWS using Terraform

### ISSUE THREAD

**Issue by jeffellin** [vmware/terraform-provider-tanzu-mission-control#37]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Currently it seems this plugin can only provision TKGm clusters via TMC using vSphere,  I would like to be able to provision clusters on other cloud providers,  most importantly AWS,  but I could see the same for other clouds.

**Comment by shobha2626** [comment]
@jeffellin we are adding the support for TKGm cluster on AWS. It will be the part of the next release which we are planning soon 👍

**Comment by shobha2626** [comment]
We now provide the support to provision TKGm AWS workload clusters from the release v.1.0.2
