### ISSUE TITLE
Data Source // tanzu-mission-control_cluster - Output parameter "attach_k8s_cluster" returns []

### ISSUE THREAD

**Issue by timdzbank** [vmware/terraform-provider-tanzu-mission-control#434]
### Describe the bug

We are fetching the data from tanzu mission control to get the kubeconfig of a workload cluster as an output.
But the parameter "attach_k8s_cluster" is empty.

```
attach_k8s_cluster      = null
```

Every other parameter is filled with correct data e.g.

```
.....
      + name                    = "cluster-0001"
      + provisioner_name        = "abc"
      + ready_wait_timeout      = "120"
      + spec                    = [
          + {
              + cluster_group       = "abc"
              + image_registry      = ""
              + proxy               = ""
              + tkg_aws             = []
              + tkg_service_vsphere = []
              + tkg_vsphere         = []
            },
        ]
      + status                  = {
          + health                = "HEALTHY"
          + infra_provider        = "VMWARE_VSPHERE"
.....
```

We are running Tanzu Kubernetes cluster self managed in our DC.

Please assist.
### Reproduction steps

1. Create the data source "tanzu-mission-control_cluster"

```terraform
data "tanzu-mission-control_cluster" "this" {
  management_cluster_name = "mgmt-clsuter"
  provisioner_name        = local.namespace
  name                    = "cluster-0001"
  ready_wait_timeout      = 120
}
```

2. Terraform plan
3. Terraform apply
4. Output of attach_k8s_cluster is empty

### Expected behavior

Output of attach_k8s_cluster is filled with the parameters of the docs

**Comment by warroyo** [comment]
The issue here is that this field is not documented properly and is only available for attached clusters. a new data source is needed for the tanzu_kubernetes_cluster type. closing this issue in favor of https://github.com/vmware/terraform-provider-tanzu-mission-control/issues/443
