### ISSUE TITLE
tanzu_kubernetes_cluster resource does not provide a data source resource as well

### ISSUE THREAD

**Issue by warroyo** [vmware/terraform-provider-tanzu-mission-control#443]
### Is your feature request related to a problem? Please describe.

currently there is no data source associated with the tanzu_kubernetes_cluster resource type. This is needed in many situations to return a kubeconfig or other info about the cluster.

### Describe the solution you'd like

a new datas source should be created for this resource

**Comment by tenthirtyam** [comment]
Resolved in #444.
