### ISSUE TITLE
terraform-provider-tanzu-mission-control_v1.1.2.exe plugin crashed

### ISSUE THREAD

**Issue by HSoulat** [vmware/terraform-provider-tanzu-mission-control#74]
### Describe the bug

│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-tanzu-mission-control_v1.1.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x222b450]

goroutine 51 [running]:
github.com/vmware/terraform-provider-tanzu-mission-control/internal/resources/cluster.dataSourceTMCClusterRead({0x27eddb8, 0xc0001925a0}, 0xc00043
5c80, {0x24562e0?, 0xc0001d31c0?})
        github.com/vmware/terraform-provider-tanzu-mission-control/internal/resources/cluster/data_source_cluster.go:136 +0xdb0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000203ce0, {0x27eddf0, 0xc0005fe450}, 0xd?, {0x24562e0, 0xc0001d31c
0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:359 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000203ce0, {0x27eddf0, 0xc0005fe450}, 0xc000435c00, {0x245
62e0, 0xc0001d31c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:578 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0002cf710, {0x27edd48?, 0xc000363740?}, 0xc0002
ad780)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1179 +0x357
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000269360, {0x27eddf0?, 0xc000483980?}, 0xc000080f00)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:657 +0x409
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x24b2520?, 0xc000269360}, {0x27eddf0, 0xc
000483980}, 0xc00007be00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b5a40, {0x27f14c0, 0xc00008a1a0}, 0xc0005f4ea0, 0xc0003c9c80, 0x333c0b0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001b5a40, {0x27f14c0, 0xc00008a1a0}, 0xc0005f4ea0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-tanzu-mission-control_v1.1.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Reproduction steps

1. terraform plan

### Expected behavior

..

**Comment by Vasundharashukla** [comment]
Hi @HSoulat, can you give me the details of the cluster you are creating, the management cluster name, provisioner name and the TMC endpoint you are using?

**Comment by shreyassreenivas** [comment]
@HSoulat , 
This bug is limited only to data source read of provisioned clusters. Attach clusters and other data resources should be working. 

Pardon the inconvenience and this will be fixed with https://github.com/vmware/terraform-provider-tanzu-mission-control/pull/76 PR.

**Comment by shreyassreenivas** [comment]
This issue has been fixed and will be available in the next release.
