### ISSUE TITLE
kubeconfig input alternate options

### ISSUE THREAD

**Issue by johnny-platform** [vmware/terraform-provider-tanzu-mission-control#77]
### Is your feature request related to a problem? Please describe.

When using the attach_cluster_with_kubeconfig you must specify a path to the kubeconfig using the kubeconfig_file variable and can't use the content of an output or block as an input to the config needed.  There are extra modules needed to create a file in order to do this and creates more dependencies.

### Describe the solution you'd like

For example, when attaching an AKS cluster, it would be nice to use the [kube_config_raw](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_cluster#kube_config_raw) or kube_config_admin_raw value as an input for the kubeconfig needed to attach a cluster to TMC.  Currently for an AKS attach, you must create the file through another method like local_file from the kube_config_raw variable and pass that file location to the TMC module.  So in the function of attach_k8s_cluster maybe have another input option that could be the content of another ouput.

**Comment by cdelashmutt-pivotal** [comment]
It could also be useful to configure the kubernetes client configuration via strings for host, the client cert, the client key, and the cluster CA.  

An existing provider that provides an example for this is hashicorp/kubernetes.  You can see an example of the way that module handles configuration at https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#credentials-config.

**Comment by Vasundharashukla** [comment]
Hi @johnny-platform, 

The support for taking kubeconfig input as a block/ kubeconfig_raw has been added to the provider with the [PR](https://github.com/vmware/terraform-provider-tanzu-mission-control/pull/125). We shall be doing a release soon that will have this feature enabled.

**Comment by Vasundharashukla** [comment]
Hi @cdelashmutt-pivotal,

We are assessing the use case of supporting kubeconfig using its components, will keep you posted on the update.

**Comment by shreyassreenivas** [comment]
This issue has been addressed and the feature request MR has been checked in. 
Should be available in the next release
